const getters = {
  sidebar: (state) => state.app.sidebar,
  size: (state) => state.app.size,
  device: (state) => state.app.device,
  dict: (state) => state.dict.dict,
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  token: (state) => state.user.token,
  avatar: (state) => state.user.avatar,
  name: (state) => state.user.name,
  introduction: (state) => state.user.introduction,
  roles: (state) => state.user.roles,
  permissions: (state) => state.user.permissions,
  permission_routes: (state) => state.permission.routes,
  divisionsTreeList: (state) => state.user.divisionsTreeList,
  allDivisionsTreeList: (state) => state.user.allDivisionsTreeList,
  mapList: (state) => state.user.mapList,
  topbarRouters: (state) => state.permission.topbarRouters,
  defaultRoutes: (state) => state.permission.defaultRoutes,
  sidebarRouters: (state) => state.permission.sidebarRouters,
  anzhiTypeDict: (state) => state.user.anzhiTypeDict,
  deptCommonDict: (state) => state.dict.deptCommonDict,
};
export default getters;
